repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.2
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: local
    hooks:
    -   id: run-tests
        name: run tests
        entry: pytest tests/
        language: system
        pass_filenames: false
        always_run: true

    -   id: test-coverage
        name: check test coverage
        entry: pytest tests/ --cov=mealplan_mcp --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
